import 'dotenv/config'
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Set SUPABASE_URL and SUPABASE_SERVICE_KEY in environment')
  process.exit(1)
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)

/**
 * Example usage (node server/generate_ticket.js) expects env variables and
 * can be invoked programmatically from an HTTP server.
 */
export async function createTicket({ name, phone, services = [], mode = 'join' }) {
  // 1) Upsert customer by phone
  const { data: customer, error: upsertErr } = await supabase
    .from('customers')
    .upsert({ name, phone }, { onConflict: 'phone' })
    .select('*')
    .maybeSingle()

  if (upsertErr) throw upsertErr

  const customer_id = customer.id

  // 2) Create visit
  const { data: visit, error: visitErr } = await supabase
    .from('visits')
    .insert({ customer_id, services })
    .select('*')
    .maybeSingle()

  if (visitErr) throw visitErr

  // 3) Create queue item; ticket_code generated by DB function default
  const { data: queueItem, error: queueErr } = await supabase
    .from('queue')
    .insert({ visit_id: visit.id })
    .select('*')
    .maybeSingle()

  if (queueErr) throw queueErr

  // compute people ahead
  const { data: ahead, error: aheadErr } = await supabase
    .from('queue')
    .select('id')
    .eq('status', 'waiting')
    .lt('created_at', queueItem.created_at)

  if (aheadErr) throw aheadErr

  const peopleAhead = (ahead || []).length

  return {
    ticket: queueItem.ticket_code,
    peopleAhead,
    expectedMinutes: (peopleAhead + 1) * 10,
    customer,
    visit: visit,
    queue: queueItem
  }
}

export default createTicket

// If run directly for quick tests
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('generate_ticket.js')) {
  const args = process.argv.slice(2)
  const name = args[0] || 'Test'
  const phone = args[1] || '01000000000'
  createTicket({ name, phone }).then(res => console.log(res)).catch(err => console.error(err))
}
